apiVersion: v2
name: valkey
description: Valkey is an open source, high-performance data structure server compatible with Redis. It supports strings, hashes, lists, sets, and sorted sets.
type: application
version: 0.1.9
appVersion: "8.1.3"
annotations:
  images: |
    - name: valkey
      image: docker.io/valkey/valkey:8.1.3
    - name: os-shell
      image: docker.io/alpine:3.19
    - name: redis-exporter
      image: docker.io/oliver006/redis_exporter:v1.45.0
  licenses: Apache-2.0
  category: database
keywords:
  - valkey
  - redis
  - database
  - cache
  - nosql
  - keyvalue
  - sentinel
  - high-performance
home: https://valkey.io/
icon: https://valkey.io/assets/images/valkey-logo.svg
sources:
  - https://github.com/valkey-io/valkey
  - https://github.com/start-codex/valkey-helm-chart
maintainers:
  - name: Valkey Community
    url: https://github.com/start-codex/valkey-helm-chart
    email: contact@valkey.io
