architecture: standalone
auth:
  enabled: true
  existingSecret: 'redis-secret'
  existingSecretPasswordKey: 'password'
standalone:
  replicaCount: 1
  persistence:
    enabled: true
    size: 8Gi
    storageClass: 'longhorn-simple'
    accessModes:
      - ReadWriteOnce
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 6379

podSecurityContext:
  fsGroup: 999
  runAsGroup: 999
  runAsUser: 999

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 999