{{- if and (eq .Values.architecture "sentinel") .Values.sentinel.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "valkey.fullname" . }}-sentinel
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.sentinel.labels" . | nindent 4 }}
  {{- with (include "valkey.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "valkey.fullname" . }}-sentinel
  minReplicas: {{ .Values.sentinel.hpa.minReplicas }}
  maxReplicas: {{ .Values.sentinel.hpa.maxReplicas }}
  metrics:
    {{- if .Values.sentinel.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.sentinel.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.sentinel.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.sentinel.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with .Values.sentinel.hpa.customMetrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.sentinel.hpa.behavior }}
  behavior:
    {{- toYaml .Values.sentinel.hpa.behavior | nindent 4 }}
  {{- end }}
{{- end }}