{{- if eq .Values.architecture "sentinel" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
  {{- with (include "valkey.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-valkey
      port: {{ .Values.master.service.port }}
      targetPort: valkey
    {{- if .Values.sentinel.enabled }}
    - name: tcp-sentinel
      port: {{ .Values.sentinel.service.sentinelPort }}
      targetPort: sentinel
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: http-metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
{{- end }}