{{- if .Release.IsUpgrade }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "valkey.fullname" . }}-pre-upgrade
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: pre-upgrade-hook
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: {{ include "valkey.fullname" . }}-pre-upgrade
      labels:
        {{- include "valkey.labels" . | nindent 8 }}
        app.kubernetes.io/component: pre-upgrade-hook
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "valkey.fullname" . }}-pre-upgrade
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      initContainers:
        {{- if eq .Values.architecture "sentinel" }}
        # Delete master StatefulSet
        - name: delete-master
          image: {{ .Values.preUpgradeHook.image.registry }}/{{ .Values.preUpgradeHook.image.repository }}:{{ .Values.preUpgradeHook.image.tag }}
          imagePullPolicy: {{ .Values.preUpgradeHook.image.pullPolicy }}
          args:
            - delete
            - statefulset
            - {{ include "valkey.fullname" . }}-master
            - --namespace={{ .Release.Namespace }}
            - --cascade=orphan
            - --ignore-not-found=true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
          {{- if .Values.preUpgradeHook.resources }}
          resources: {{- toYaml .Values.preUpgradeHook.resources | nindent 12 }}
          {{- end }}
        # Delete replica StatefulSet
        - name: delete-replica
          image: {{ .Values.preUpgradeHook.image.registry }}/{{ .Values.preUpgradeHook.image.repository }}:{{ .Values.preUpgradeHook.image.tag }}
          imagePullPolicy: {{ .Values.preUpgradeHook.image.pullPolicy }}
          args:
            - delete
            - statefulset
            - {{ include "valkey.fullname" . }}-replica
            - --namespace={{ .Release.Namespace }}
            - --cascade=orphan
            - --ignore-not-found=true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
          {{- if .Values.preUpgradeHook.resources }}
          resources: {{- toYaml .Values.preUpgradeHook.resources | nindent 12 }}
          {{- end }}
        # Delete sentinel StatefulSet
        - name: delete-sentinel
          image: {{ .Values.preUpgradeHook.image.registry }}/{{ .Values.preUpgradeHook.image.repository }}:{{ .Values.preUpgradeHook.image.tag }}
          imagePullPolicy: {{ .Values.preUpgradeHook.image.pullPolicy }}
          args:
            - delete
            - statefulset
            - {{ include "valkey.fullname" . }}-sentinel
            - --namespace={{ .Release.Namespace }}
            - --cascade=orphan
            - --ignore-not-found=true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
          {{- if .Values.preUpgradeHook.resources }}
          resources: {{- toYaml .Values.preUpgradeHook.resources | nindent 12 }}
          {{- end }}
        {{- else }}
        # Delete standalone StatefulSet
        - name: delete-standalone
          image: {{ .Values.preUpgradeHook.image.registry }}/{{ .Values.preUpgradeHook.image.repository }}:{{ .Values.preUpgradeHook.image.tag }}
          imagePullPolicy: {{ .Values.preUpgradeHook.image.pullPolicy }}
          args:
            - delete
            - statefulset
            - {{ include "valkey.fullname" . }}
            - --namespace={{ .Release.Namespace }}
            - --cascade=orphan
            - --ignore-not-found=true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
          {{- if .Values.preUpgradeHook.resources }}
          resources: {{- toYaml .Values.preUpgradeHook.resources | nindent 12 }}
          {{- end }}
        {{- end }}
      containers:
        # Final container just to complete the job successfully
        - name: complete
          image: {{ .Values.preUpgradeHook.image.registry }}/{{ .Values.preUpgradeHook.image.repository }}:{{ .Values.preUpgradeHook.image.tag }}
          imagePullPolicy: {{ .Values.preUpgradeHook.image.pullPolicy }}
          args:
            - version
            - --client=true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
          {{- if .Values.preUpgradeHook.resources }}
          resources: {{- toYaml .Values.preUpgradeHook.resources | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "valkey.fullname" . }}-pre-upgrade
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: pre-upgrade-hook
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "valkey.fullname" . }}-pre-upgrade
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: pre-upgrade-hook
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "valkey.fullname" . }}-pre-upgrade
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: pre-upgrade-hook
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "valkey.fullname" . }}-pre-upgrade
subjects:
  - kind: ServiceAccount
    name: {{ include "valkey.fullname" . }}-pre-upgrade
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
