{{- if eq .Values.architecture "sentinel" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-replica" (include "valkey.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.replica.labels" . | nindent 4 }}
  {{- with (include "valkey.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  valkey.conf: |
    # Valkey replica configuration
    bind 0.0.0.0
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300

    # Memory configuration
    maxmemory-policy allkeys-lru

    # Persistence
    save ""

    # Logging
    loglevel notice

    # Security
    protected-mode no
{{- if .Values.auth.enabled }}

    # Authentication
    requirepass ${VALKEY_PASSWORD}
    masterauth ${VALKEY_PASSWORD}
{{- end }}
{{- end }}