{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "valkey.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  {{- with (include "valkey.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "valkey.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "valkey.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}