{{- if .Values.serviceBinding.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}-svcbind
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: svcbind
  annotations:
    service.binding/type: "valkey"
    service.binding/provider: "valkey"
  {{- with (include "valkey.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  provider: {{ "valkey" | b64enc }}
  type: {{ "valkey" | b64enc }}
  {{- if eq .Values.architecture "standalone" }}
  host: {{ (printf "%s.%s.svc.%s" (include "valkey.fullname" .) .Release.Namespace (.Values.clusterDomain | default "cluster.local")) | b64enc }}
  port: {{ .Values.standalone.service.port | toString | b64enc }}
  {{- else }}
  host: {{ (printf "%s.%s.svc.%s" (include "valkey.master.serviceName" .) .Release.Namespace (.Values.clusterDomain | default "cluster.local")) | b64enc }}
  port: {{ .Values.master.service.port | toString | b64enc }}
  {{- if .Values.sentinel.enabled }}
  sentinel-host: {{ (printf "%s.%s.svc.%s" (include "valkey.sentinel.serviceName" .) .Release.Namespace (.Values.clusterDomain | default "cluster.local")) | b64enc }}
  sentinel-port: {{ .Values.sentinel.service.sentinelPort | toString | b64enc }}
  {{- end }}
  {{- end }}
  {{- if include "valkey.auth.enabled" . }}
  password: {{ include "valkey.secretPasswordKey" . | b64enc }}
  {{- end }}
  database: {{ "0" | b64enc }}
  uri: {{ printf "valkey://%s:%d/0" (include "valkey.fullname" .) (include "valkey.port" . | int) | b64enc }}
{{- end }}