{{- if eq .Values.architecture "sentinel" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-sentinel" (include "valkey.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.sentinel.labels" . | nindent 4 }}
  {{- with (include "valkey.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.sentinel.replicaCount }}
  selector:
    matchLabels:
      {{- include "valkey.sentinel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "valkey.sentinel.selectorLabels" . | nindent 8 }}
      {{- with (include "valkey.annotations" .) }}
      annotations:
        {{- . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/sentinel-configmap.yaml") . | sha256sum }}
        {{- if .Values.auth.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
    spec:
      {{- if or .Values.image.pullSecrets .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- if .Values.image.pullSecrets }}
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
        {{- else if .Values.global.imagePullSecrets }}
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "valkey.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: sentinel
          image: {{ include "valkey.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - /bin/bash
          args:
            - -c
            - |
              cp /opt/valkey/etc/sentinel.conf /tmp/sentinel.conf
              echo "sentinel monitor mymaster {{ include "valkey.master.serviceName" . }} 6379 {{ .Values.sentinel.quorum }}" >> /tmp/sentinel.conf
              echo "sentinel down-after-milliseconds mymaster {{ .Values.sentinel.downAfterMilliseconds }}" >> /tmp/sentinel.conf
              echo "sentinel parallel-syncs mymaster {{ .Values.sentinel.parallelSyncs }}" >> /tmp/sentinel.conf
              echo "sentinel failover-timeout mymaster {{ .Values.sentinel.failoverTimeout }}" >> /tmp/sentinel.conf
              {{- if .Values.auth.enabled }}
              echo "sentinel auth-pass mymaster $VALKEY_PASSWORD" >> /tmp/sentinel.conf
              {{- end }}
              valkey-sentinel /tmp/sentinel.conf
          env:
            {{- if .Values.auth.enabled }}
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "valkey.secretName" . }}
                  key: {{ include "valkey.secretPasswordKey" . }}
            {{- end }}
          ports:
            - name: sentinel
              containerPort: 26379
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - |
                  valkey-cli -p 26379 ping
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - |
                  valkey-cli -p 26379 ping
          {{- if .Values.sentinel.resources }}
          resources: {{- toYaml .Values.sentinel.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /opt/valkey/etc/sentinel.conf
              subPath: sentinel.conf
            - name: tmp
              mountPath: /tmp
      {{- with .Values.sentinel.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sentinel.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sentinel.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ printf "%s-sentinel" (include "valkey.fullname" .) }}
        - name: tmp
          emptyDir: {}
{{- end }}