{{- if eq .Values.architecture "sentinel" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-sentinel" (include "valkey.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.sentinel.labels" . | nindent 4 }}
  {{- with (include "valkey.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  sentinel.conf: |
{{- .Values.sentinel.configuration | nindent 4 }}
{{- end }}