{{- if eq .Values.architecture "standalone" }}
{{- include "valkey.validateArchitecture" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valkey.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.standalone.labels" . | nindent 4 }}
  {{- with (include "valkey.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.standalone.replicaCount }}
  selector:
    matchLabels:
      {{- include "valkey.standalone.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "valkey.standalone.selectorLabels" . | nindent 8 }}
      {{- with (include "valkey.annotations" .) }}
      annotations:
        {{- . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/standalone-configmap.yaml") . | sha256sum }}
        {{- if .Values.auth.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "valkey.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.sysctls.enabled }}
      initContainers:
        - name: init-sysctl
          image: {{ include "valkey.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              install_packages procps
              sysctl -w net.core.somaxconn=65535
          securityContext:
            privileged: true
            runAsUser: 0
          {{- if .Values.sysctls.resources }}
          resources: {{- toYaml .Values.sysctls.resources | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- if and .Values.volumePermissions.enabled .Values.standalone.persistence.enabled }}
        - name: volume-permissions
          image: {{ .Values.volumePermissions.image.registry }}/{{ .Values.volumePermissions.image.repository }}:{{ .Values.volumePermissions.image.tag }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy }}
          command:
            - /bin/bash
            - -ec
            - |
              chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /data
          securityContext:
            runAsUser: 0
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: valkey-data
              mountPath: /data
      {{- end }}
      containers:
        - name: valkey
          image: {{ include "valkey.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - /bin/bash
          args:
            - -c
            - |
              {{- if .Values.auth.enabled }}
              export REDISCLI_AUTH="$VALKEY_PASSWORD"
              {{- end }}
              valkey-server /opt/valkey/etc/valkey.conf
          env:
            {{- if .Values.auth.enabled }}
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "valkey.secretName" . }}
                  key: {{ include "valkey.secretPasswordKey" . }}
            {{- end }}
          ports:
            - name: valkey
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - |
                  {{- if .Values.auth.enabled }}
                  valkey-cli -a "$VALKEY_PASSWORD" ping
                  {{- else }}
                  valkey-cli ping
                  {{- end }}
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - |
                  {{- if .Values.auth.enabled }}
                  valkey-cli -a "$VALKEY_PASSWORD" ping
                  {{- else }}
                  valkey-cli ping
                  {{- end }}
          {{- if .Values.standalone.resources }}
          resources: {{- toYaml .Values.standalone.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: valkey-data
              mountPath: /data
            - name: config
              mountPath: /opt/valkey/etc/valkey.conf
              subPath: valkey.conf
            - name: tmp
              mountPath: /tmp
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: {{ include "valkey.metrics.image" . }}
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          env:
            - name: REDIS_ADDR
              value: "redis://127.0.0.1:6379"
            {{- if .Values.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "valkey.secretName" . }}
                  key: {{ include "valkey.secretPasswordKey" . }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: 9121
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 5
            timeoutSeconds: 1
          {{- if .Values.metrics.resources }}
          resources: {{- toYaml .Values.metrics.resources | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- with .Values.standalone.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.standalone.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.standalone.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "valkey.fullname" . }}
        - name: tmp
          emptyDir: {}
        {{- if .Values.standalone.persistence.enabled }}
        - name: valkey-data
          persistentVolumeClaim:
            claimName: {{ include "valkey.fullname" . }}
        {{- else }}
        - name: valkey-data
          emptyDir: {}
        {{- end }}
{{- end }}