{{- if eq .Values.architecture "standalone" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.standalone.labels" . | nindent 4 }}
  {{- with .Values.standalone.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "valkey.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.standalone.service.type }}
  ports:
    - port: {{ .Values.standalone.service.port }}
      targetPort: {{ .Values.standalone.service.targetPort }}
      protocol: TCP
      name: valkey
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "valkey.standalone.selectorLabels" . | nindent 4 }}
{{- end }}