{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}-tls
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  {{- with (include "valkey.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.tls.cert }}
  {{ .Values.tls.certFilename }}: {{ .Values.tls.cert | b64enc }}
  {{- end }}
  {{- if .Values.tls.key }}
  {{ .Values.tls.certKeyFilename }}: {{ .Values.tls.key | b64enc }}
  {{- end }}
  {{- if .Values.tls.caCert }}
  {{ .Values.tls.certCAFilename }}: {{ .Values.tls.caCert | b64enc }}
  {{- end }}
  {{- if .Values.tls.dhParams }}
  {{ .Values.tls.dhParamsFilename }}: {{ .Values.tls.dhParams | b64enc }}
  {{- end }}
{{- end }}