{{- if or (eq .Values.architecture "standalone") (eq .Values.architecture "sentinel") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.master.serviceName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.master.labels" . | nindent 4 }}
  {{- with .Values.master.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "valkey.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.master.service.type }}
  ports:
    - port: {{ .Values.master.service.port }}
      targetPort: {{ .Values.master.service.targetPort }}
      protocol: TCP
      name: valkey
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    {{- end }}
  selector:
    {{- include "valkey.master.selectorLabels" . | nindent 4 }}
{{- end }}