name: Test Chart

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - name: Lint chart
        run: |
          helm lint .
          echo "✅ Chart lint passed"

      - name: Test chart templates
        run: |
          echo "Testing standalone mode..."
          helm template test . --set architecture=standalone > /dev/null
          echo "✅ Standalone template generation passed"

          echo "Testing sentinel mode..."
          helm template test . --set architecture=sentinel --set auth.enabled=true --set auth.password=test > /dev/null
          echo "✅ Sentinel template generation passed"

      - name: Package chart
        run: |
          helm package .
          ls -la *.tgz
          echo "✅ Chart packaging passed"

      - name: Test installation (template only)
        run: |
          echo "Testing template generation with default values..."
          helm template test-valkey . > /dev/null
          echo "✅ Template generation with default values passed"

          echo "Testing template generation with custom values..."
          cat > test-values.yaml << 'EOF'
          architecture: standalone
          auth:
            enabled: true
            password: "testpassword"
          standalone:
            persistence:
              storageClass: "standard"
          EOF
          helm template test-valkey . -f test-values.yaml > /dev/null
          echo "✅ Template generation with custom values passed"